    - name: Start Ngrok Tunnel (in background)
      run: |
        Start-Job -ScriptBlock { .\ngrok.exe tcp 3389 }
        Start-Sleep -Seconds 25

    - name: Get RDP address from Ngrok
      run: |
        $tries = 0
        do {
          try {
            $response = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
            $success = $true
          } catch {
            Start-Sleep -Seconds 5
            $tries++
          }
        } while (-not $success -and $tries -lt 6)

        if (-not $success) {
          Write-Error "❌ Failed to connect to Ngrok API after multiple attempts."
          exit 1
        }

        $rdpUrl = $response.tunnels[0].public_url -replace "tcp://", ""
        Write-Output "✅ RDP is ready! Connect using this address:"
        Write-Output $rdpUrl
