name: RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download and setup ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath ngrok
          # Use the NGROK_AUTH_TOKEN secret for security
          .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          Write-Host "Ngrok setup complete."

      - name: Enable RDP and create user
        run: |
          # Use the RDP_PASSWORD secret for security
          $username = "kamel123"
          $password = "${{ secrets.RDP_PASSWORD }}"

          # Create user and add to administrators group
          net user $username $password /add
          net localgroup administrators $username /add
          Write-Host "User '$username' created and added to administrators."

          # Enable Remote Desktop Connections
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Write-Host "RDP enabled and firewall rule configured."
        # Keep this step running indefinitely to maintain the ngrok tunnel
        # This is a common pattern for keeping RDP sessions alive on GitHub Actions
        # until the workflow is cancelled or times out.
        - name: Keep ngrok tunnel open
          run: |
            .\ngrok\ngrok.exe tcp 3389 --log "ngrok.log"
          # This step will run indefinitely. You will need to manually cancel the workflow
          # on GitHub Actions when you are done with the RDP session.
          # The timeout-minutes property can be added to the job if you want it to stop after a certain time.
          # For example: jobs: build: timeout-minutes: 360 (for 6 hours)
